review vlc 3.0.6

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -35,7 +35,6 @@ usage()
 	echo "  --enable-ad-clauses configure to build packages with advertising clauses"
 	echo "                   (USE AT YOUR OWN LEGAL RISKS)"
 	echo "  --disable-optim  disable optimization in libraries"
-	echo "  --enable-pdb     generate debug information in PDB format"
 }
 
 BUILD=
@@ -50,7 +49,6 @@ GPL="1"
 GNUV3="1"
 AD_CLAUSES=
 WITH_OPTIMIZATION="1"
-ENABLE_PDB=
 
 if test ! -f "../../contrib/src/main.mak"
 then
@@ -85,9 +83,6 @@ do
 			;;
 		--disable-optim)
 			WITH_OPTIMIZATION=
-			;;
-		--enable-pdb)
-			ENABLE_PDB=1
 			;;
 		--enable-small)
 			ENABLE_SMALL=1
@@ -125,7 +120,7 @@ fi
 if test -z "$BUILD"
 then
 	echo -n "Guessing build system... "
-	BUILD="`${CC:-cc} -dumpmachine | sed s/windows-gnu/mingw32/`"
+	BUILD="`${CC:-cc} -dumpmachine`"
 	if test -z "$BUILD"; then
 		echo "FAIL!"
 		exit 1
@@ -169,9 +164,8 @@ fi
 #
 # Prepare files
 #
-echo "Creating makefile..."
-test -e Makefile && unlink Makefile
-exec 3>Makefile || exit $?
+echo "Creating configuration file... config.mak"
+exec 3>config.mak || exit $?
 cat >&3 << EOF
 # This file was automatically generated.
 # Any change will be overwritten if ../bootstrap is run again.
@@ -224,17 +218,38 @@ check_ios_sdk()
 
 check_macosx_sdk()
 {
-   if [ -z "$SDKROOT" ]; then
-      SDKROOT=$(xcrun --show-sdk-path)
+   if [ -z "${OSX_VERSION}" ]
+   then
+      OSX_VERSION=`xcrun --show-sdk-version`
+      echo "OSX_VERSION not specified, assuming $OSX_VERSION"
+   fi
+   if test -z "$SDKROOT"
+   then
+      SDKROOT=`xcode-select -print-path`/Platforms/MacOSX.platform/Developer/SDKs/MacOSX$OSX_VERSION.sdk
       echo "SDKROOT not specified, assuming $SDKROOT"
    fi
 
-   if [ ! -d "$SDKROOT" ]; then
-      echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
+   if [ ! -d "${SDKROOT}" ]
+   then
+      SDKROOT_NOT_FOUND=`xcode-select -print-path`/Platforms/MacOSX.platform/Developer/SDKs/MacOSX$OSX_VERSION.sdk
+      SDKROOT=`xcode-select -print-path`/SDKs/MacOSX$OSX_VERSION.sdk
+      echo "SDKROOT not found at $SDKROOT_NOT_FOUND, trying $SDKROOT"
+   fi
+   if [ ! -d "${SDKROOT}" ]
+   then
+      SDKROOT_NOT_FOUND="$SDKROOT"
+      SDKROOT=`xcrun --show-sdk-path`
+      echo "SDKROOT not found at $SDKROOT_NOT_FOUND, trying $SDKROOT"
+   fi
+
+   if [ ! -d "${SDKROOT}" ]
+   then
+      echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
       exit 1
    fi
 
    add_make "MACOSX_SDK=${SDKROOT}"
+   add_make "OSX_VERSION ?= ${OSX_VERSION}"
 }
 
 check_android_sdk()
@@ -271,7 +286,6 @@ test -z "$GPL" || add_make_enabled "GPL"
 test -z "$GNUV3" || add_make_enabled "GNUV3"
 test -z "$AD_CLAUSES" || add_make_enabled "AD_CLAUSES"
 test -z "$WITH_OPTIMIZATION" || add_make_enabled "WITH_OPTIMIZATION"
-test -z "$ENABLE_PDB" || add_make_enabled "ENABLE_PDB"
 test "`uname -o 2>/dev/null`" != "Msys" || add_make "CMAKE_GENERATOR := -G \"MSYS Makefiles\""
 
 #
@@ -289,23 +303,9 @@ case "${OS}" in
 			add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_FPU"
 
 			case "${HOST}" in
-			    *armv7s*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7s"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm64*|*aarch64*)
-			    add_make "PLATFORM_SHORT_ARCH := arm64"
-			    ;;
-			    *x86_64*)
-			    add_make "PLATFORM_SHORT_ARCH := x86_64"
-			    ;;
-			    *86*)
-			    add_make "PLATFORM_SHORT_ARCH := i386"
-			    ;;
+				*arm*)
+				add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+				;;
 			esac;
 		fi
 		if test "$BUILDFORTVOS"
@@ -379,18 +379,13 @@ case "${OS}" in
 	*solaris*)
 		add_make_enabled "HAVE_SOLARIS"
 		;;
-	*nacl*)
-		add_make_enabled "HAVE_NACL"
-		;;
 esac
 
 #
 # Results output
 #
-echo TOPSRC = .. >> Makefile
-echo TOPSRC_BUILT = ../.. >> Makefile
-echo TOPDST = .. >> Makefile
-echo include $\(TOPSRC\)/src/main.mak >> Makefile
+test -e Makefile && unlink Makefile
+ln -sf ../../contrib/src/main.mak Makefile || exit $?
 echo "Bootstrap completed."
 make help
 mkdir -p ../../contrib/tarballs || exit $?
